// generated by stringer -type=OpCode; DO NOT EDIT

package genregex

import "fmt"

const _OpCode_name = "CharMatchJumpSplitSaveNop"

var _OpCode_index = [...]uint8{0, 4, 9, 13, 18, 22, 25}

func (i OpCode) String() string {
	if i+1 >= OpCode(len(_OpCode_index)) {
		return fmt.Sprintf("OpCode(%d)", i)
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
